Import('env')

env.Append(
    LIBS = [
        'physics_engine',
    ],
)
env.Tool('glfw')

target = 'example'
source = (
    'src/main.c',
)

example = env.Program(target, source)

Return('example')
