import platform

Import('env')

target = 'physics_engine'
source = (
    'src/integrator.c',
    'src/loop.c',
)

env.Append(
    CPPPATH = [
        'src/$MODE',
    ],
)

if platform.system().lower() == 'darwin':
    lib = env.SharedLibrary(target, source)
else:
    lib = env.StaticLibrary(target, source)

Return('lib')
