import platform

Import('env')

target = 'physics_engine'
source = (
    'integrator.c',
)

if platform.system().lower() == 'darwin':
    lib = env.SharedLibrary(target, source)
else:
    lib = env.StaticLibrary(target, source)

Return('lib')
